/** Complete shared catalog: every supported language implements every key. */
export interface MessageCatalog {
  readonly 'atlas.travel': string
  readonly 'atlas.camp-view': string

  readonly 'loadout.equip': string
  readonly 'loadout.unequip': string
  readonly 'loadout.cost': string
  readonly 'loadout.blocked': string
  readonly 'loadout.full': string
  readonly 'loadout.lore.probe': string
  readonly 'loadout.effects.probe': string
  readonly 'loadout.lore.scanner': string
  readonly 'loadout.effects.scanner': string
  readonly 'loadout.lore.guard': string
  readonly 'loadout.effects.guard': string
  readonly 'loadout.lore.medical-kit': string
  readonly 'loadout.effects.medical-kit': string
  readonly 'loadout.lore.steel-blade': string
  readonly 'loadout.effects.steel-blade': string
  readonly 'loadout.lore.plated-vest': string
  readonly 'loadout.effects.plated-vest': string
  readonly 'loadout.lore.focus-lens': string
  readonly 'loadout.effects.focus-lens': string
  readonly 'loadout.lore.clearing-hook': string
  readonly 'loadout.effects.clearing-hook': string
  readonly 'loadout.lore.field-boots': string
  readonly 'loadout.effects.field-boots': string
  readonly 'loadout.lore.field-radio': string
  readonly 'loadout.effects.field-radio': string
  readonly 'loadout.lore.sonar': string
  readonly 'loadout.effects.sonar': string

  readonly 'ferry.destination': string
  readonly 'current.title': string
  readonly 'current.guide': string
  readonly 'current.legend': string
  readonly 'current.held': string
  readonly 'current.moving': string

  readonly 'ferry.objective': string
  readonly 'ferry.exit-ready': string
  readonly 'ferry.progress': string
  readonly 'ferry.receiver': string
  readonly 'ferry.junction': string
  readonly 'ferry.door': string
  readonly 'ferry.recorded': string
  readonly 'ferry.guide-intro': string
  readonly 'ferry.guide-switch-title': string
  readonly 'ferry.guide-switch': string
  readonly 'ferry.guide-record-title': string
  readonly 'ferry.guide-record': string

  readonly 'dialogue.places': string
  readonly 'dialogue.items': string
  readonly 'dialogue.warnings': string
  readonly 'rail.rumor-1': string
  readonly 'rail.rumor-2': string
  readonly 'rail.rumor-3': string
  readonly 'ferry.title': string
  readonly 'ferry.task': string
  readonly 'ferry.detail': string
  readonly 'ferry.lead-1': string
  readonly 'ferry.lead-2': string
  readonly 'ferry.lead-3': string
  readonly 'ferry.floor-1': string
  readonly 'ferry.floor-2': string
  readonly 'ferry.floor-3': string
  readonly 'ferry.entry-1': string
  readonly 'ferry.entry-2': string
  readonly 'ferry.entry-3': string
  readonly 'ferry.banks-1': string
  readonly 'ferry.banks-2': string
  readonly 'ferry.banks-3': string
  readonly 'ferry.gate-1': string
  readonly 'ferry.gate-2': string
  readonly 'ferry.gate-3': string
  readonly 'ferry.end-1': string
  readonly 'ferry.end-2': string
  readonly 'ferry.end-3': string

  readonly 'story.main-title': string
  readonly 'story.side-title': string
  readonly 'recollection.back-settings': string
  readonly 'signal.tower-response-1': string
  readonly 'signal.tower-response-2': string
  readonly 'signal.tower-response-3': string
  readonly 'signal.tower-response-4': string
  readonly 'signal.tower-response-5': string

  readonly 'recollection.existing': string
  readonly 'recollection.resume-expedition': string

  readonly 'recollection.task': string
  readonly 'recollection.task-camp': string
  readonly 'recollection.task-lantern': string

  readonly 'recollection.camp': string
  readonly 'recollection.title': string
  readonly 'recollection.lantern': string
  readonly 'recollection.floors': string
  readonly 'recollection.bosses': string
  readonly 'recollection.ordinary': string
  readonly 'recollection.relay': string
  readonly 'recollection.routing': string
  readonly 'recollection.ordinary-note': string
  readonly 'recollection.relay-note': string
  readonly 'recollection.routing-note': string
  readonly 'recollection.relays-progress': string
  readonly 'recollection.floor-locked': string
  readonly 'recollection.boss-locked': string
  readonly 'recollection.choose': string
  readonly 'recollection.begin': string
  readonly 'recollection.resume': string
  readonly 'recollection.locked': string
  readonly 'recollection.return': string
  readonly 'recollection.loadout': string
  readonly 'recollection.chapter': string
  readonly 'recollection.arrival-1': string
  readonly 'recollection.arrival-2': string
  readonly 'recollection.arrival-3': string
  readonly 'recollection.arrival-4': string
  readonly 'recollection.arrival-5': string
  readonly 'recollection.arrival-6': string
  readonly 'recollection.light-1': string
  readonly 'recollection.light-2': string
  readonly 'recollection.light-3': string
  readonly 'recollection.light-4': string
  readonly 'recollection.light-5': string

  readonly 'story.lesson-title': string
  readonly 'story.lesson-inspect': string
  readonly 'story.lesson-open-mouse': string
  readonly 'story.lesson-open-touch': string
  readonly 'story.lesson-travel': string
  readonly 'battle-lesson.guardian-pylon': string
  readonly 'battle-lesson.guardian-core': string
  readonly 'battle-lesson.guardian-approach': string

  readonly 'rescuer.name': string
  readonly 'rescuer.note': string
  readonly 'rescuer.skill': string
  readonly 'rescuer.skill-note': string
  readonly 'rescuer.no-corridor': string
  readonly 'rescuer.landing': string
  readonly 'rail.guide-brake': string
  readonly 'rail.diagram-covered': string
  readonly 'rail.diagram-clear': string
  readonly 'rail.diagram-switch': string
  readonly 'rail.diagram-brake': string
  readonly 'rail.diagram-home': string
  readonly 'exit.closed': string
  readonly 'exit.open': string
  readonly 'battle-lesson.title': string
  readonly 'battle-lesson.points': string
  readonly 'battle-lesson.move': string
  readonly 'battle-lesson.no-move': string
  readonly 'battle-lesson.dodge': string
  readonly 'battle-lesson.turn': string
  readonly 'battle-lesson.combat': string
  readonly 'battle-lesson.prepare': string
  readonly 'battle-lesson.attack': string
  readonly 'battle-lesson.reopen': string

  readonly 'rail.camp-1': string
  readonly 'rail.camp-2': string
  readonly 'rail.camp-3': string
  readonly 'rail.reward': string
  readonly 'rail.title': string
  readonly 'rail.task': string
  readonly 'rail.task-detail': string
  readonly 'rail.toma': string
  readonly 'rail.floor-1': string
  readonly 'rail.floor-2': string
  readonly 'rail.floor-3': string
  readonly 'rail.exit-ready': string
  readonly 'rail.objective': string
  readonly 'rail.objective-rescue': string
  readonly 'rail.drive': string
  readonly 'rail.reverse': string
  readonly 'rail.drive-detail': string
  readonly 'rail.reverse-detail': string
  readonly 'rail.turnout': string
  readonly 'rail.brake': string
  readonly 'rail.home-stop': string
  readonly 'rail.help': string
  readonly 'rail.progress': string
  readonly 'rail.stop-covered': string
  readonly 'rail.stop-blocked': string
  readonly 'rail.stop-turnout': string
  readonly 'rail.stop-station': string
  readonly 'rail.stop-buffer': string
  readonly 'rail.guide-intro': string
  readonly 'rail.guide-clear': string
  readonly 'rail.guide-route': string
  readonly 'rail.guide-rescue': string
  readonly 'rail.entry-1': string
  readonly 'rail.entry-2': string
  readonly 'rail.entry-3': string
  readonly 'rail.entry-4': string
  readonly 'rail.brakes-1': string
  readonly 'rail.brakes-2': string
  readonly 'rail.brakes-3': string
  readonly 'rail.rescue-1': string
  readonly 'rail.rescue-2': string
  readonly 'rail.rescue-3': string
  readonly 'rail.home-1': string
  readonly 'rail.home-2': string
  readonly 'rail.home-3': string
  readonly 'rail.home-4': string
  readonly 'finale.control-title': string
  readonly 'finale.pass-title': string
  readonly 'finale.bridge': string
  readonly 'finale.pass': string
  readonly 'finale.shortcut': string
  readonly 'finale.control-task': string
  readonly 'finale.control-detail': string
  readonly 'finale.pass-task': string
  readonly 'finale.pass-detail': string
  readonly 'finale.control-1': string
  readonly 'finale.control-2': string
  readonly 'finale.control-3': string
  readonly 'finale.pass-1': string
  readonly 'finale.pass-2': string
  readonly 'finale.pass-3': string
  readonly 'finale.receiver': string
  readonly 'finale.guardian-pressure': string
  readonly 'finale.recorded': string
  readonly 'finale.objective': string
  readonly 'finale.exit-ready': string
  readonly 'finale.progress': string
  readonly 'finale.guide-intro': string
  readonly 'finale.guide-title': string
  readonly 'finale.guide-record': string
  readonly 'finale.control-entry-1': string
  readonly 'finale.control-entry-2': string
  readonly 'finale.control-entry-3': string
  readonly 'finale.control-entry-4': string
  readonly 'finale.control-line-1': string
  readonly 'finale.control-line-2': string
  readonly 'finale.control-line-3': string
  readonly 'finale.control-heart-1': string
  readonly 'finale.control-heart-2': string
  readonly 'finale.control-heart-3': string
  readonly 'finale.control-restored-1': string
  readonly 'finale.control-restored-2': string
  readonly 'finale.control-restored-3': string
  readonly 'finale.control-restored-4': string
  readonly 'finale.pass-entry-1': string
  readonly 'finale.pass-entry-2': string
  readonly 'finale.pass-warning-1': string
  readonly 'finale.pass-warning-2': string
  readonly 'finale.pass-warning-3': string
  readonly 'finale.pass-guardian-1': string
  readonly 'finale.pass-guardian-2': string
  readonly 'finale.pass-guardian-3': string
  readonly 'finale.pass-guardian-4': string
  readonly 'finale.pass-open-1': string
  readonly 'finale.pass-open-2': string
  readonly 'finale.pass-open-3': string
  readonly 'finale.pass-open-4': string
  readonly 'finale.pass-open-5': string
  readonly 'finale.pass-open-6': string
  readonly 'finale.pass-open-7': string
  readonly 'finale.pass-open-8': string
  readonly 'finale.pass-open-9': string
  readonly 'finale.pass-open-10': string
  readonly 'finale.chapter-camp-1': string
  readonly 'finale.chapter-camp-2': string
  readonly 'finale.chapter-camp-3': string
  readonly 'finale.chapter-camp-4': string
  readonly 'finale.chapter-camp-5': string

  readonly 'waterway.title': string
  readonly 'waterway.task': string
  readonly 'waterway.task-detail': string
  readonly 'waterway.floor-1': string
  readonly 'waterway.floor-2': string
  readonly 'waterway.floor-3': string
  readonly 'waterway.receiver': string
  readonly 'waterway.recorded': string
  readonly 'waterway.objective': string
  readonly 'waterway.exit-ready': string
  readonly 'waterway.progress': string
  readonly 'waterway.guide-intro': string
  readonly 'waterway.guide-record-title': string
  readonly 'waterway.guide-record': string
  readonly 'waterway.entry-1': string
  readonly 'waterway.entry-2': string
  readonly 'waterway.entry-3': string
  readonly 'waterway.drained-1': string
  readonly 'waterway.drained-2': string
  readonly 'waterway.drained-3': string
  readonly 'waterway.locks-1': string
  readonly 'waterway.locks-2': string
  readonly 'waterway.locks-3': string
  readonly 'waterway.call-1': string
  readonly 'waterway.call-2': string
  readonly 'waterway.call-3': string
  readonly 'waterway.found-1': string
  readonly 'waterway.found-2': string
  readonly 'waterway.found-3': string
  readonly 'waterway.found-4': string
  readonly 'waterway.found-5': string
  readonly 'waterway.found-6': string
  readonly 'waterway.found-7': string
  readonly 'waterway.found-8': string
  readonly 'waterway.found-9': string
  readonly 'waterway.camp-1': string
  readonly 'waterway.camp-2': string
  readonly 'waterway.camp-3': string
  readonly 'waterway.camp-4': string

  readonly 'ridge.recording': string
  readonly 'ridge.title': string
  readonly 'ridge.task': string
  readonly 'ridge.task-detail': string
  readonly 'ridge.floor-1': string
  readonly 'ridge.floor-2': string
  readonly 'ridge.floor-3': string
  readonly 'ridge.covered': string
  readonly 'ridge.clue': string
  readonly 'ridge.unpowered': string
  readonly 'ridge.recorded': string
  readonly 'ridge.ready': string
  readonly 'ridge.objective': string
  readonly 'ridge.exit-ready': string
  readonly 'ridge.progress': string
  readonly 'ridge.network': string
  readonly 'ridge.guide-intro': string
  readonly 'ridge.guide-clear-title': string
  readonly 'ridge.guide-clear': string
  readonly 'ridge.guide-switch-title': string
  readonly 'ridge.guide-switch': string
  readonly 'ridge.guide-record-title': string
  readonly 'ridge.guide-record': string
  readonly 'ridge.guide-upstream': string
  readonly 'ridge.guide-wiring': string
  readonly 'ridge.junction': string
  readonly 'ridge.receiver': string
  readonly 'ridge.door': string
  readonly 'ridge.open': string
  readonly 'ridge.closed': string
  readonly 'ridge.entry-1': string
  readonly 'ridge.entry-2': string
  readonly 'ridge.entry-3': string
  readonly 'ridge.reading-1': string
  readonly 'ridge.reading-2': string
  readonly 'ridge.reading-3': string
  readonly 'ridge.pair-1': string
  readonly 'ridge.pair-2': string
  readonly 'ridge.pair-3': string
  readonly 'ridge.beacon-1': string
  readonly 'ridge.beacon-2': string
  readonly 'ridge.beacon-3': string
  readonly 'ridge.found-1': string
  readonly 'ridge.found-2': string
  readonly 'ridge.found-3': string
  readonly 'ridge.found-4': string
  readonly 'ridge.found-5': string
  readonly 'ridge.camp-1': string
  readonly 'ridge.camp-2': string
  readonly 'ridge.camp-3': string
  readonly 'signal.camp-3': string
  readonly 'signal.camp-4': string

  readonly 'story.haul-load': string
  readonly 'story.go-together': string
  readonly 'story.lift-answer': string
  readonly 'story.brake': string
  readonly 'story.winch': string
  readonly 'story.haul-track': string
  readonly 'story.gate-closed': string
  readonly 'story.mechanism-done': string
  readonly 'story.mechanism-operate': string
  readonly 'story.mechanism-locked': string
  readonly 'story.mechanism-help': string
  readonly 'story.mechanism-ready': string
  readonly 'story.brake-scene-1': string
  readonly 'story.brake-scene-2': string
  readonly 'story.release-scene-1': string
  readonly 'story.release-scene-2': string
  readonly 'story.winch-scene-1': string
  readonly 'story.winch-scene-2': string
  readonly 'signal.title': string
  readonly 'signal.floor-1': string
  readonly 'signal.floor-2': string
  readonly 'signal.floor-3': string
  readonly 'signal.relay': string
  readonly 'signal.gate': string
  readonly 'signal.released': string
  readonly 'signal.ready': string
  readonly 'signal.solve': string
  readonly 'signal.record': string
  readonly 'signal.optional': string
  readonly 'signal.continue': string
  readonly 'signal.nia': string
  readonly 'signal.player': string
  readonly 'signal.lumi': string
  readonly 'signal.guardian': string
  readonly 'signal.complete': string
  readonly 'signal.entry-1': string
  readonly 'signal.entry-2': string
  readonly 'signal.entry-3': string
  readonly 'signal.connected-1': string
  readonly 'signal.connected-2': string
  readonly 'signal.connected-3': string
  readonly 'signal.connected-4': string
  readonly 'signal.archive-1': string
  readonly 'signal.archive-2': string
  readonly 'signal.archive-3': string
  readonly 'signal.record-1': string
  readonly 'signal.record-2': string
  readonly 'signal.prison-1': string
  readonly 'signal.prison-2': string
  readonly 'signal.rescued-1': string
  readonly 'signal.rescued-2': string
  readonly 'signal.rescued-3-saved': string
  readonly 'signal.rescued-3-skipped': string
  readonly 'signal.camp-1': string
  readonly 'signal.camp-2-saved': string
  readonly 'signal.camp-2-skipped': string
  readonly 'story.north-road': string
  readonly 'story.lift': string
  readonly 'story.world-road': string
  readonly 'story.road-task': string
  readonly 'story.road-detail': string
  readonly 'story.north-start-1': string
  readonly 'story.north-start-2': string
  readonly 'story.north-found-1': string
  readonly 'story.north-found-2': string
  readonly 'story.north-report-1': string
  readonly 'story.north-report-2': string

  readonly 'story.atlas-watchtower': string
  readonly 'story.atlas-uncharted': string
  readonly 'story.atlas-zoom': string
  readonly 'story.atlas-zoom-in': string
  readonly 'story.atlas-zoom-out': string
  readonly 'story.atlas-fit': string
  readonly 'story.atlas-tree': string
  readonly 'story.atlas-district-trail': string
  readonly 'story.atlas-district-camp': string
  readonly 'story.atlas-district-quarry': string
  readonly 'story.atlas-district-west': string
  readonly 'story.atlas-region': string
  readonly 'story.atlas-reedbank': string
  readonly 'story.atlas-unsurveyed': string
  readonly 'story.atlas-switch': string
  readonly 'story.atlas-world': string
  readonly 'story.atlas-legend': string
  readonly 'story.atlas-local': string
  readonly 'story.atlas-woodland': string
  readonly 'story.atlas-here': string
  readonly 'story.atlas-route': string
  readonly 'story.atlas-route-closed': string
  readonly 'story.atlas-route-one-way': string
  readonly 'story.atlas-enter': string
  readonly 'story.quest-accepted': string
  readonly 'story.no-quests': string
  readonly 'story.no-accepted': string
  readonly 'story.pin': string
  readonly 'story.unpin': string
  readonly 'story.map': string
  readonly 'story.no-map': string
  readonly 'story.map-received': string
  readonly 'story.quest-main-detail': string
  readonly 'story.quest-side-detail': string
  readonly 'story.quest-guide-detail': string
  readonly 'story.quest-location': string
  readonly 'story.flag-mouse': string
  readonly 'campaign.lesson-move': string
  readonly 'campaign.lesson-title': string
  readonly 'campaign.lesson-enter': string
  readonly 'campaign.lesson-probe': string
  readonly 'campaign.lesson-scan': string
  readonly 'campaign.lesson-skill': string
  readonly 'campaign.lesson-open': string
  readonly 'campaign.lesson-begin': string
  readonly 'campaign.lesson-skip': string
  readonly 'campaign.enter': string
  readonly 'campaign.title': string
  readonly 'campaign.abandon': string
  readonly 'campaign.abandon-note': string
  readonly 'campaign.exit': string
  readonly 'campaign.abandoned': string
  readonly 'campaign.leave': string
  readonly 'campaign.objective': string
  readonly 'story.flag-touch': string
  readonly 'story.quarry-yard': string
  readonly 'story.quarry-passage': string
  readonly 'story.quarry-machine': string
  readonly 'story.tower-landing': string
  readonly 'story.spindle': string
  readonly 'story.repair-task': string
  readonly 'story.repair-detail': string
  readonly 'story.repair-return': string
  readonly 'story.climb-task': string
  readonly 'story.climb-detail': string
  readonly 'story.quarry-lead': string
  readonly 'story.spindle-found': string
  readonly 'story.lift-fixed': string
  readonly 'story.tower-arrival': string
  readonly 'story.chord-mouse': string
  readonly 'story.chord-touch': string
  readonly 'story.map-unvisited': string
  readonly 'story.return-bag': string
  readonly 'story.open-eyes': string
  readonly 'story.dialogue-next': string
  readonly 'story.dialogue-read': string
  readonly 'story.where-am-i': string
  readonly 'story.other-world': string
  readonly 'story.found-bag': string
  readonly 'story.keep-bag': string
  readonly 'story.home-question': string
  readonly 'story.thanks': string
  readonly 'story.prologue': string
  readonly 'story.camp': string
  readonly 'story.guide': string
  readonly 'story.awakening': string
  readonly 'story.trail': string
  readonly 'story.approach': string
  readonly 'story.wake-line': string
  readonly 'story.read-task': string
  readonly 'story.flag-line': string
  readonly 'story.flag-task': string
  readonly 'story.open-line': string
  readonly 'story.open-task': string
  readonly 'story.travel-line': string
  readonly 'story.travel-task': string
  readonly 'story.trail-line': string
  readonly 'story.trail-task': string
  readonly 'story.approach-line': string
  readonly 'story.approach-task': string
  readonly 'story.arrival-line': string
  readonly 'story.camp-task': string
  readonly 'story.guide-line': string
  readonly 'story.camp-ready': string
  readonly 'story.road-line': string
  readonly 'story.continue': string
  readonly 'story.enter-camp': string
  readonly 'story.explore': string
  readonly 'story.flag': string
  readonly 'story.route': string
  readonly 'story.lesson': string
  readonly 'story.hurt': string
  readonly 'story.fallen': string
  readonly 'story.restart': string
  readonly 'story.retry': string
  readonly 'story.satchel': string
  readonly 'story.satchel-found': string
  readonly 'story.all-tasks': string
  readonly 'story.tasks': string
  readonly 'story.main-task': string
  readonly 'story.side-task': string
  readonly 'story.meet-task': string
  readonly 'story.done': string
  readonly 'story.optional': string
  readonly 'story.pending': string
  readonly 'story.missed': string
  readonly 'story.back-camp': string
  readonly 'story.facility': string
  readonly 'story.lantern': string
  readonly 'story.road': string
  readonly 'story.wall': string
  readonly 'story.covered': string
  readonly 'story.safe': string
  readonly 'story.marked': string
  readonly 'story.pulse': string
  readonly 'story.clue': string
  readonly 'story.health': string
  readonly 'story.storage': string
  readonly 'story.inspect': string

  readonly 'home.title': string
  readonly 'home.note': string
  readonly 'home.free': string
  readonly 'home.expedition-note': string
  readonly 'home.free-note': string
  readonly 'home.enter-expedition': string
  readonly 'home.choose-mode': string
  readonly 'home.back': string
  readonly 'home.settings': string
  readonly 'home.directory-note': string
  readonly 'home.saved': string
  readonly 'home.classic-note': string
  readonly 'home.twin-note': string
  readonly 'home.sonar-note': string
  readonly 'home.survey-note': string
  readonly 'board.remaining-mines': string
  readonly 'tide.held': string
  readonly 'tide.until': string
  readonly 'tide.name': string
  readonly 'tide.core': string
  readonly 'tide.anchor': string
  readonly 'tide.anchor-hint': string
  readonly 'tide.hint': string
  readonly 'tide.deduce': string
  readonly 'tide.fight': string
  readonly 'tide.shuffle-note': string
  readonly 'tide.status': string
  readonly 'tide.open': string
  readonly 'tide.shield': string
  readonly 'tide.anchored': string
  readonly 'tide.shuffled': string
  readonly 'tide.broken': string
  readonly 'tide.phase': string
  readonly 'tide.scene-0': string
  readonly 'tide.scene-1': string
  readonly 'tide.scene-2': string
  readonly 'tide.scene-3': string
  readonly 'tide.scene-4': string
  readonly 'matrix.quiet': string
  readonly 'matrix.open-hint': string
  readonly 'matrix.hunt': string
  readonly 'matrix.hunt-note': string
  readonly 'matrix.precise': string
  readonly 'matrix.precise-note': string
  readonly 'matrix.precise-effect': string
  readonly 'matrix.name': string
  readonly 'matrix.deduce': string
  readonly 'matrix.calibrate': string
  readonly 'matrix.fight': string
  readonly 'matrix.forecast': string
  readonly 'matrix.gaps': string
  readonly 'matrix.shield': string
  readonly 'matrix.phase': string
  readonly 'matrix.armed': string
  readonly 'matrix.shifted': string
  readonly 'matrix.status': string
  readonly 'matrix.legend': string
  readonly 'matrix.scene-0': string
  readonly 'matrix.scene-1': string
  readonly 'matrix.scene-2': string
  readonly 'matrix.scene-3': string
  readonly 'matrix.scene-4': string
  readonly 'matrix.observe': string
  readonly 'matrix.attune': string
  readonly 'matrix.attune-hint': string
  readonly 'matrix.observation-hint': string
  readonly 'matrix.region': string
  readonly 'matrix.ground': string
  readonly 'matrix.region-only': string
  readonly 'matrix.note': string
  readonly 'matrix.empty-cell': string
  readonly 'matrix.unresolved': string
  readonly 'matrix.select': string
  readonly 'matrix.collected': string
  readonly 'matrix.collected-event': string
  readonly 'matrix.empty-event': string

  readonly 'survey.mines': string
  readonly 'survey.title': string
  readonly 'survey.intro': string
  readonly 'survey.opening': string
  readonly 'survey.legend': string
  readonly 'survey.hint': string
  readonly 'survey.bookkeeping': string
  readonly 'survey.line-action': string
  readonly 'survey.line': string
  readonly 'survey.moves': string
  readonly 'survey.remaining': string
  readonly 'survey.zoom': string
  readonly 'survey.fit': string
  readonly 'survey.win': string
  readonly 'survey.loss': string
  readonly 'survey.rank-hint': string
  readonly 'survey.no-records': string
  readonly 'survey.recovered': string
  readonly 'survey.limit': string
  readonly 'survey.chord': string
  readonly 'survey.lesson-title': string
  readonly 'survey.lesson-overlap-title': string
  readonly 'survey.lesson-overlap': string
  readonly 'survey.lesson-column-title': string
  readonly 'survey.lesson-column': string
  readonly 'survey.lesson-column-right': string
  readonly 'survey.lesson-chord-title': string
  readonly 'survey.lesson-chord-mode': string
  readonly 'survey.lesson-chord': string
  readonly 'survey.lesson-gap-title': string
  readonly 'survey.lesson-reveal-mode': string
  readonly 'survey.lesson-gap': string
  readonly 'survey.lesson-ending': string
  readonly 'echo.shifted': string
  readonly 'echo.phase-break': string
  readonly 'echo.rhythm': string

  readonly 'echo.hunt': string
  readonly 'echo.hunt-note': string
  readonly 'echo.flawless': string
  readonly 'echo.flawless-note': string
  readonly 'echo.precise': string
  readonly 'echo.precise-note': string
  readonly 'echo.flawless-effect': string
  readonly 'echo.precise-effect': string

  readonly 'echo.scene-0': string
  readonly 'echo.scene-1': string
  readonly 'echo.scene-2': string
  readonly 'echo.scene-3': string
  readonly 'echo.scene-4': string
  readonly 'echo.scene-5': string
  readonly 'echo.scene-6': string
  readonly 'echo.scene-7': string
  readonly 'echo.scene-8': string

  readonly 'echo.locate': string
  readonly 'echo.shell': string
  readonly 'echo.fight': string
  readonly 'echo.loan': string
  readonly 'echo.body': string
  readonly 'echo.candidates': string
  readonly 'echo.obscured': string
  readonly 'echo.reading': string
  readonly 'echo.present': string
  readonly 'echo.absent': string
  readonly 'echo.stale': string
  readonly 'echo.phase-note': string

  readonly 'sonar-equipment.name': string
  readonly 'sonar-equipment.note': string
  readonly 'echo.name': string
  readonly 'echo.status': string

  readonly 'battle-guide.approach-a-revealed-hourglass-and-return-a': string
  readonly 'battle-guide.approach-the-core-and-activate-it-to': string
  readonly 'battle-guide.clear-eggs-before-they-hatch-and-avoid': string
  readonly 'battle-guide.compare-the-boards-a-mine-on-one': string
  readonly 'battle-guide.disable-a-seal-to-expose-the-twin': string
  readonly 'battle-guide.fewer-nests-mean-less-armor-and-healing': string
  readonly 'battle-guide.flag-nearby-mines-and-destroy-a-nest': string
  readonly 'battle-guide.flag-the-mines-around-both-pylons-then': string
  readonly 'battle-guide.full-rules': string
  readonly 'battle-guide.leave-the-marked-cells-before-the-countdown': string
  readonly 'battle-guide.move-1-cell-reveal-1-strike-2': string
  readonly 'battle-guide.open-a-route-to-an-anchor-then': string
  readonly 'battle-guide.strike-switch-realms-strike-the-other-twin': string
  readonly 'battle-guide.strike-then-leave-your-echo-it-repeats': string
  readonly 'battle-guide.strike-while-exposed-leave-the-red-cells': string
  readonly 'battle-guide.the-crash-breaks-its-armor-approach-and': string
  readonly 'battle-guide.three-moves-to-learn-the-fight': string
  readonly 'battle-guide.use-the-preparation-turn-to-leave-the': string
  readonly 'battle-presentation.action-points': string
  readonly 'battle-presentation.approach-and-prime-the-core-1-ap': string
  readonly 'battle-presentation.attack': string
  readonly 'battle-presentation.base-5-attack-0-defense-3-ap': string
  readonly 'battle-presentation.base-stats-10-health-5-attack-0': string
  readonly 'battle-presentation.bastion-guardian': string
  readonly 'battle-presentation.boss-defeated-full-health-1-shield': string
  readonly 'battle-presentation.brace-1-ap': string
  readonly 'battle-presentation.brace-reduces-this-turn-s-enemy-damage': string
  readonly 'battle-presentation.brood-queen': string
  readonly 'battle-presentation.build-effects': string
  readonly 'battle-presentation.control-disabled': string
  readonly 'battle-presentation.control-reveal-and-flag-neighboring-mines': string
  readonly 'battle-presentation.controls-2': string
  readonly 'battle-presentation.core-exposed': string
  readonly 'battle-presentation.core-open-turns': string
  readonly 'battle-presentation.defense': string
  readonly 'battle-presentation.defenses': string
  readonly 'battle-presentation.each-nest-gives-3-armor-and-heals': string
  readonly 'battle-presentation.eggs-hatch-after-two-turns-hatchlings-advance': string
  readonly 'battle-presentation.end-turn': string
  readonly 'battle-presentation.enemy-attack-forecast': string
  readonly 'battle-presentation.nests-3-armor-regen': string
  readonly 'battle-presentation.reveal-each-control-and-flag-its-neighboring': string
  readonly 'battle-presentation.reveal-nests-and-flag-their-neighboring-mines': string
  readonly 'battle-presentation.row-column-and-cross-attacks-remain-fixed': string
  readonly 'battle-presentation.scout-the-nearest-active-objective-with-undiscovered': string
  readonly 'battle-presentation.strike-2-ap': string
  readonly 'battle-presentation.the-amber-control-reduces-future-attacks-from': string
  readonly 'battle-presentation.turn': string
  readonly 'battle-presentation.turn-ap': string
  readonly 'board-controls.chord': string
  readonly 'board-controls.flag': string
  readonly 'board-controls.gestures': string
  readonly 'board-controls.label': string
  readonly 'board-controls.reveal': string
  readonly 'board-controls.safe': string
  readonly 'board-controls.tap-to-cycle': string
  readonly 'board-help.chord': string
  readonly 'board-help.edge': string
  readonly 'board-help.expeditionChord': string
  readonly 'board-help.extensions': string
  readonly 'board-help.gestures': string
  readonly 'board-help.keyboard': string
  readonly 'board-help.known': string
  readonly 'board-help.note': string
  readonly 'board-help.triggered': string
  readonly 'board-help.vimium': string
  readonly 'boss-prologue.at-the-threshold': string
  readonly 'boss-prologue.continue': string
  readonly 'boss-prologue.enter-battle': string
  readonly 'boss-prologue.explorer': string
  readonly 'boss-prologue.label': string
  readonly 'boss-prologue.previous': string
  readonly 'boss-prologue.skip-arrival': string
  readonly 'boss-scripts.a-buried-anchor-answers-the-pulse-with': string
  readonly 'boss-scripts.a-hunger-with-many-mouths': string
  readonly 'boss-scripts.a-mark-appears-beneath-your-feet-you': string
  readonly 'boss-scripts.a-moment-left-behind': string
  readonly 'boss-scripts.a-repeated-blow-is-only-an-invitation': string
  readonly 'boss-scripts.a-seal-glows-in-the-amber-room': string
  readonly 'boss-scripts.a-thread-catches-your-sleeve-then-another': string
  readonly 'boss-scripts.an-answer-on-the-other-side': string
  readonly 'boss-scripts.an-egg-rolls-from-the-nearest-nest': string
  readonly 'boss-scripts.bastion-guardian': string
  readonly 'boss-scripts.beyond-the-stairs-something-immense-draws-a': string
  readonly 'boss-scripts.borrow-the-enemy-s-strength': string
  readonly 'boss-scripts.brood-queen': string
  readonly 'boss-scripts.clock-mage-clepsydra': string
  readonly 'boss-scripts.cut-the-silk-if-you-like-my': string
  readonly 'boss-scripts.do-not-hurry-i-have-already-reserved': string
  readonly 'boss-scripts.even-your-footsteps-belong-to-my-field': string
  readonly 'boss-scripts.i-can-see-their-shadows-gathering-ahead': string
  readonly 'boss-scripts.i-hear-that-little-anchor-singing-when': string
  readonly 'boss-scripts.it-has-chosen-a-place-and-a': string
  readonly 'boss-scripts.magnetic-knight': string
  readonly 'boss-scripts.mirror-twins': string
  readonly 'boss-scripts.my-blade-rings-against-its-armor-not': string
  readonly 'boss-scripts.my-boots-slide-before-i-lift-them': string
  readonly 'boss-scripts.no-one-passes-the-walls-remember-every': string
  readonly 'boss-scripts.one-feeds-the-blows-the-other-keeps': string
  readonly 'boss-scripts.quiet-feet-warm-blood-you-have-come': string
  readonly 'boss-scripts.something-of-each-strike-stays-behind-and': string
  readonly 'boss-scripts.the-amber-light-brightens-the-guardian-s': string
  readonly 'boss-scripts.the-door-that-learned-to-breathe': string
  readonly 'boss-scripts.the-guardian-settles-its-weight-both-lights': string
  readonly 'boss-scripts.the-knight-closes-its-fists-for-an': string
  readonly 'boss-scripts.the-last-grain-of-sand-falls-upward': string
  readonly 'boss-scripts.the-mirror-clears-two-paths-wait-and': string
  readonly 'boss-scripts.the-needle-in-your-compass-turns-sideways': string
  readonly 'boss-scripts.the-nests-are-more-than-nurseries-if': string
  readonly 'boss-scripts.the-pull-is-gathering-not-striking-yet': string
  readonly 'boss-scripts.the-queen-lifts-herself-from-the-floor': string
  readonly 'boss-scripts.the-rooms-share-a-shape-but-not': string
  readonly 'boss-scripts.the-wound-i-made-is-closing-something': string
  readonly 'boss-scripts.their-protection-comes-from-the-other-room': string
  readonly 'boss-scripts.then-i-change-partners-remember-where-i': string
  readonly 'boss-scripts.then-i-will-read-the-floor-before': string
  readonly 'boss-scripts.then-send-its-spell-back-to-shatter': string
  readonly 'boss-scripts.those-scars-it-has-been-drawn-here': string
  readonly 'boss-scripts.touch-my-clocks-if-you-must-borrowed': string
  readonly 'boss-scripts.which-of-us-did-you-come-to': string
  readonly 'boss-scripts.you-watch-the-lamps-instead-of-the': string
  readonly 'boss-scripts.your-hand-drops-but-the-outline-it': string
  readonly 'boss-scripts.your-reflection-takes-one-more-step-after': string
  readonly 'brood-board.nest-destroyed': string
  readonly 'brood-board.nest-reveal-and-flag-nearby-mines-to': string
  readonly 'brood-board.next-hatchling-position': string
  readonly 'brood-copy.egg-hatches-in-turns-clear-adjacent-for': string
  readonly 'brood-copy.hatchling-clear-adjacent-for-1-ap': string
  readonly 'brood-copy.web-clear-adjacent-for-1-ap': string
  readonly 'camp-copy.achievements': string
  readonly 'camp-copy.all': string
  readonly 'camp-copy.back-to-camp': string
  readonly 'camp-copy.choose-your-explorer-and-skill': string
  readonly 'camp-copy.count-floors': string
  readonly 'camp-copy.count-unlocked': string
  readonly 'camp-copy.equipment': string
  readonly 'camp-copy.loadout': string
  readonly 'camp-copy.loadout-points': string
  readonly 'camp-copy.missions': string
  readonly 'camp-copy.need-count-more-supplies': string
  readonly 'camp-copy.no-equipment-selected': string
  readonly 'camp-copy.purchase': string
  readonly 'camp-copy.ready-for-departure': string
  readonly 'camp-copy.relics': string
  readonly 'camp-copy.select-an-item-to-see-its-effect': string
  readonly 'camp-copy.shop': string
  readonly 'camp-copy.unlock-the-workshop-before-buying-and-equipping': string
  readonly 'camp-template.ready': string
  readonly 'clock-board.echo': string
  readonly 'clock-board.echo-move': string
  readonly 'clock-board.echo-pending-damage': string
  readonly 'clock-board.echo-ready': string
  readonly 'clock-board.hourglass-reveal-approach-return-earliest-spell-1': string
  readonly 'clock-board.last-turn-echo-returned-spell': string
  readonly 'clock-board.spent-hourglass-walkable': string
  readonly 'clock-copy.an-adjacent-or-occupied-revealed-hourglass-returns': string
  readonly 'clock-copy.barrier-return-a-spell-first': string
  readonly 'clock-copy.clock-hand-damage-3': string
  readonly 'clock-copy.clock-mage-clepsydra': string
  readonly 'clock-copy.delayed-casting': string
  readonly 'clock-copy.dual-countdown': string
  readonly 'clock-copy.each-turn-starts-with-a-walkable-echo': string
  readonly 'clock-copy.hourglasses-3': string
  readonly 'clock-copy.in-turn-ends': string
  readonly 'clock-copy.marks-deal-3-damage-after-two-turn': string
  readonly 'clock-copy.recovery-no-new-spell': string
  readonly 'clock-copy.return-a-spell-with-an-hourglass-to': string
  readonly 'clock-copy.returned-spell-boss-damage-6': string
  readonly 'clock-copy.spell-returned-deadline-unchanged': string
  readonly 'clock-copy.this-turn-end': string
  readonly 'clock-copy.time-mark-damage-3': string
  readonly 'combat-build-copy.1-ap-every-combat-turn-up-to': string
  readonly 'combat-build-copy.1-loadout-point-starting-and-maximum-health': string
  readonly 'combat-build-copy.1-loadout-point-the-first-control-or': string
  readonly 'combat-build-copy.1-loadout-point-the-first-web-egg': string
  readonly 'combat-build-copy.2-loadout-points-1-ap-on-even': string
  readonly 'combat-build-copy.2-loadout-points-attack-2': string
  readonly 'combat-build-copy.2-loadout-points-defense-1-against-enemy': string
  readonly 'combat-build-copy.add-attack-defense-and-action-point-relics': string
  readonly 'combat-build-copy.attack-3-for-this-expedition': string
  readonly 'combat-build-copy.battle-manual': string
  readonly 'combat-build-copy.clearing-hook': string
  readonly 'combat-build-copy.defense-1-against-enemy-attacks-for-this': string
  readonly 'combat-build-copy.endurance-training': string
  readonly 'combat-build-copy.field-boots': string
  readonly 'combat-build-copy.focus-lens': string
  readonly 'combat-build-copy.layered-armor': string
  readonly 'combat-build-copy.medical-kit': string
  readonly 'combat-build-copy.mines-deal-5-damage-each-shield-absorbs': string
  readonly 'combat-build-copy.one-purchase-only-base-attack-1-on': string
  readonly 'combat-build-copy.one-purchase-only-starting-and-maximum-health': string
  readonly 'combat-build-copy.plated-vest': string
  readonly 'combat-build-copy.steel-blade': string
  readonly 'combat-build-copy.tactics-hourglass': string
  readonly 'combat-build-copy.tempered-edge': string
  readonly 'combat-build-copy.weapon-training': string
  readonly 'journey-relic-copy.a-row-scan-confirming-at-least-2': string
  readonly 'journey-relic-copy.add-breach-sigil-and-duelist-edge-recover': string
  readonly 'journey-relic-copy.add-marching-boots-and-shelter-cloak-cheaper': string
  readonly 'journey-relic-copy.add-probe-recycler-and-spare-coil-recover': string
  readonly 'journey-relic-copy.add-reserve-watch-and-second-hand-bank': string
  readonly 'journey-relic-copy.add-skill-capacitor-and-emergency-gears-link': string
  readonly 'journey-relic-copy.add-trail-thread-and-landmark-lens-earn': string
  readonly 'journey-relic-copy.after-surviving-the-third-combat-turn-gain': string
  readonly 'journey-relic-copy.breach-sigil': string
  readonly 'journey-relic-copy.cartographer-charts': string
  readonly 'journey-relic-copy.chronologist-dials': string
  readonly 'journey-relic-copy.duelist-edge': string
  readonly 'journey-relic-copy.duelist-marks': string
  readonly 'journey-relic-copy.emergency-gears': string
  readonly 'journey-relic-copy.end-a-combat-turn-outside-the-warning': string
  readonly 'journey-relic-copy.first-control-or-seal-disabled-or-anchor': string
  readonly 'journey-relic-copy.first-strike-each-floor-4-damage': string
  readonly 'journey-relic-copy.in-combat-your-first-walk-of-2': string
  readonly 'journey-relic-copy.landmark-lens': string
  readonly 'journey-relic-copy.marching-boots': string
  readonly 'journey-relic-copy.mechanist-gears': string
  readonly 'journey-relic-copy.once-per-floor-end-a-turn-with': string
  readonly 'journey-relic-copy.probe-recycler': string
  readonly 'journey-relic-copy.refund-the-first-probe-each-floor-that': string
  readonly 'journey-relic-copy.reserve-watch': string
  readonly 'journey-relic-copy.salvager-kit': string
  readonly 'journey-relic-copy.second-hand': string
  readonly 'journey-relic-copy.shelter-cloak': string
  readonly 'journey-relic-copy.skill-capacitor': string
  readonly 'journey-relic-copy.spare-coil': string
  readonly 'journey-relic-copy.the-first-chest-collected-each-floor-surveys': string
  readonly 'journey-relic-copy.trail-thread': string
  readonly 'journey-relic-copy.use-a-row-scan-while-out-of': string
  readonly 'journey-relic-copy.using-your-profession-skill-grants-1-scan': string
  readonly 'journey-relic-copy.visit-12-new-safe-squares-to-gain': string
  readonly 'journey-relic-copy.wayfarer-tokens': string
  readonly 'magnetic-board.anchor-reveal-and-flag-surrounding-mines': string
  readonly 'magnetic-board.calibrated-anchor-enter-to-ground-click-again': string
  readonly 'magnetic-board.detonated-mine-walkable-crater': string
  readonly 'magnetic-copy.a-crash-opens-the-entire-3-3': string
  readonly 'magnetic-copy.activation-cancels-the-pulse-the-first-end': string
  readonly 'magnetic-copy.anchor-calibrated-lure-committed': string
  readonly 'magnetic-copy.arrows-show-the-next-magnetic-pulse-blue': string
  readonly 'magnetic-copy.attract': string
  readonly 'magnetic-copy.brace-for-1-ap-to-reduce-forced': string
  readonly 'magnetic-copy.charge-at-end-turn-leave-the-route': string
  readonly 'magnetic-copy.charging-one-full-escape-turn-after-end': string
  readonly 'magnetic-copy.clear-a-route-to-an-anchor-calibrate': string
  readonly 'magnetic-copy.collision-base-3-damage-reduced-by-defense': string
  readonly 'magnetic-copy.core-exposed-turns': string
  readonly 'magnetic-copy.defeated': string
  readonly 'magnetic-copy.grounded-resist-displacement': string
  readonly 'magnetic-copy.horizontal': string
  readonly 'magnetic-copy.known-mine-on-the-route': string
  readonly 'magnetic-copy.magnetic-knight': string
  readonly 'magnetic-copy.projected-landing': string
  readonly 'magnetic-copy.projected-route-unverified-cells': string
  readonly 'magnetic-copy.recharge-no-pulse': string
  readonly 'magnetic-copy.repel': string
  readonly 'magnetic-copy.reveal-an-anchor-and-flag-its-surrounding': string
  readonly 'magnetic-copy.vertical': string
  readonly 'milestone-copy.abyss-veteran': string
  readonly 'milestone-copy.acquire-8-different-relics-across-expeditions-offers': string
  readonly 'milestone-copy.against-the-clock': string
  readonly 'milestone-copy.beyond-the-entrance': string
  readonly 'milestone-copy.beyond-the-mirror': string
  readonly 'milestone-copy.boss-challenger': string
  readonly 'milestone-copy.boss-hunter': string
  readonly 'milestone-copy.break-the-bastion': string
  readonly 'milestone-copy.cache-runner': string
  readonly 'milestone-copy.cache-seeker': string
  readonly 'milestone-copy.clear-5-floors-across-expeditions': string
  readonly 'milestone-copy.clock-hunt': string
  readonly 'milestone-copy.collect-3-treasure-chests-across-expeditions': string
  readonly 'milestone-copy.deep-descent': string
  readonly 'milestone-copy.defeat-10-bosses-across-expeditions': string
  readonly 'milestone-copy.defeat-both-twins-without-losing-health-revival': string
  readonly 'milestone-copy.defeat-four-different-boss-families': string
  readonly 'milestone-copy.defeat-the-bastion-without-losing-health-revival': string
  readonly 'milestone-copy.defeat-the-brood-queen-without-clearing-any': string
  readonly 'milestone-copy.defeat-the-clock-boss-using-exactly-one': string
  readonly 'milestone-copy.defeat-the-magnetic-boss-without-being-pushed': string
  readonly 'milestone-copy.defeat-the-queen-while-leaving-at-least': string
  readonly 'milestone-copy.defeat-this-boss-once': string
  readonly 'milestone-copy.defeat-your-first-boss': string
  readonly 'milestone-copy.demolition-expert': string
  readonly 'milestone-copy.depth-legend': string
  readonly 'milestone-copy.field-practice': string
  readonly 'milestone-copy.first-challenger': string
  readonly 'milestone-copy.first-footsteps': string
  readonly 'milestone-copy.four-legends': string
  readonly 'milestone-copy.homeward-bound': string
  readonly 'milestone-copy.into-the-abyss': string
  readonly 'milestone-copy.into-the-nest': string
  readonly 'milestone-copy.long-road': string
  readonly 'milestone-copy.lure-a-charge-into-at-least-one': string
  readonly 'milestone-copy.magnet-hunt': string
  readonly 'milestone-copy.master-of-magnetism': string
  readonly 'milestone-copy.queen-hunt': string
  readonly 'milestone-copy.relic-curator': string
  readonly 'milestone-copy.relic-museum': string
  readonly 'milestone-copy.return-route': string
  readonly 'milestone-copy.rift-pioneer': string
  readonly 'milestone-copy.seasoned-explorer': string
  readonly 'milestone-copy.skill-adept': string
  readonly 'milestone-copy.skill-legend': string
  readonly 'milestone-copy.skill-master': string
  readonly 'milestone-copy.skill-student': string
  readonly 'milestone-copy.successfully-use-a-profession-skill-3-times': string
  readonly 'milestone-copy.total-1-expedition-victory': string
  readonly 'milestone-copy.total-10-chests-collected': string
  readonly 'milestone-copy.total-10-successful-profession-skills': string
  readonly 'milestone-copy.total-12-floors-cleared': string
  readonly 'milestone-copy.total-150-floors-cleared': string
  readonly 'milestone-copy.total-150-new-safe-squares-visited': string
  readonly 'milestone-copy.total-1500-new-safe-squares-visited': string
  readonly 'milestone-copy.total-20-different-relics-acquired': string
  readonly 'milestone-copy.total-200-chests-collected': string
  readonly 'milestone-copy.total-200-successful-profession-skills': string
  readonly 'milestone-copy.total-25-chests-collected': string
  readonly 'milestone-copy.total-25-floors-cleared': string
  readonly 'milestone-copy.total-25-successful-profession-skills': string
  readonly 'milestone-copy.total-3-bosses-defeated': string
  readonly 'milestone-copy.total-5-abyss-victories': string
  readonly 'milestone-copy.total-50-floors-cleared': string
  readonly 'milestone-copy.total-500-new-safe-squares-visited': string
  readonly 'milestone-copy.total-60-new-safe-squares-visited': string
  readonly 'milestone-copy.total-75-chests-collected': string
  readonly 'milestone-copy.total-75-successful-profession-skills': string
  readonly 'milestone-copy.trail-apprentice': string
  readonly 'milestone-copy.trail-guide': string
  readonly 'milestone-copy.treasure-legend': string
  readonly 'milestone-copy.treasure-scout': string
  readonly 'milestone-copy.treasure-vault': string
  readonly 'milestone-copy.twin-hunt': string
  readonly 'milestone-copy.untouched-bulwark': string
  readonly 'milestone-copy.visit-20-new-safe-squares-across-expeditions': string
  readonly 'milestone-copy.web-walker': string
  readonly 'milestone-copy.win-3-expeditions-existing-camp-victories-count': string
  readonly 'milestone-copy.win-an-expedition-on-abyss-difficulty': string
  readonly 'milestone-copy.world-walker': string
  readonly 'milestone-notices.achievement': string
  readonly 'milestone-notices.completed': string
  readonly 'milestone-notices.dismiss': string
  readonly 'milestone-notices.halfway-there': string
  readonly 'milestone-notices.mission': string
  readonly 'milestone-template.claim-reward': string
  readonly 'milestone-template.claimed': string
  readonly 'milestone-template.completed': string
  readonly 'milestone-template.in-progress': string
  readonly 'milestone-template.keep-exploring': string
  readonly 'milestone-template.ready-to-claim': string
  readonly 'milestone-template.title': string
  readonly 'mirror-board.compare-shift-to-play': string
  readonly 'mirror-board.explore-here': string
  readonly 'mirror-board.seal-disabled': string
  readonly 'mirror-board.seal-protects-the-opposite-twin': string
  readonly 'mirror-copy.compare-both-realms-disable-each-seal-to': string
  readonly 'mirror-copy.dawn': string
  readonly 'mirror-copy.dawn-alternates-rows-and-columns-dusk-alternates': string
  readonly 'mirror-copy.defeated': string
  readonly 'mirror-copy.dusk': string
  readonly 'mirror-copy.exposed': string
  readonly 'mirror-copy.mirror-seal-protects-the-opposite-twin': string
  readonly 'mirror-copy.mirror-twins': string
  readonly 'mirror-copy.protected-by-seal': string
  readonly 'mirror-copy.reflecting-strike-the-other-twin': string
  readonly 'mirror-copy.reveal-a-seal-correctly-flag-every-neighboring': string
  readonly 'mirror-copy.seal-disabled-opposite-twin-exposed': string
  readonly 'mirror-copy.shift-costs-1-ap-and-resumes-your': string
  readonly 'mirror-copy.the-same-coordinate-cannot-contain-a-mine': string
  readonly 'mirror-copy.while-both-twins-live-striking-one-activates': string
  readonly 'mirror-template.attacks-resolve-at-end-turn-both-recharge': string
  readonly 'mirror-template.mirror-twins': string
  readonly 'mirror-template.recharging-no-enemy-attacks-this-turn': string
  readonly 'profession-skill-copy.available-during-exploration': string
  readonly 'profession-skill-copy.check-the-cost-and-resource-caps': string
  readonly 'profession-skill-copy.choose-a-revealed-safe-landing-two-squares': string
  readonly 'profession-skill-copy.column-survey': string
  readonly 'profession-skill-copy.confirm-mines-and-safe-cells-in-the': string
  readonly 'profession-skill-copy.confirm-mines-and-safe-cells-in-your': string
  readonly 'profession-skill-copy.excavate': string
  readonly 'profession-skill-copy.field-repair': string
  readonly 'profession-skill-copy.first-use-places-an-anchor-at-your': string
  readonly 'profession-skill-copy.move-away-from-the-anchor-its-landing': string
  readonly 'profession-skill-copy.no-new-information-here-reposition-or-explore': string
  readonly 'profession-skill-copy.open-rift': string
  readonly 'profession-skill-copy.return-anchor': string
  readonly 'profession-skill-copy.reveal-a-safe-landing-across-a-confirmed': string
  readonly 'profession-skill-copy.scout-the-nearest-uncollected-chest-s-3': string
  readonly 'profession-skill-copy.spend-1-scan-to-gain-1-shield': string
  readonly 'profession-skill-copy.spend-1-shield-to-confirm-mines-and': string
  readonly 'profession-skill-copy.spend-1-shield-to-gain-1-probe': string
  readonly 'profession-skill-copy.trail-light': string
  readonly 'profession-skill-copy.transmute': string
  readonly 'profession-skill-copy.use-once-per-floor': string
  readonly 'profession-skill-copy.used-refreshes-next-floor': string
  readonly 'profession-skill-copy.watchtower': string
  readonly 'profession-skill-template.cross-to': string
  readonly 'profession-skill-template.next-use-place-anchor': string
  readonly 'profession-skill-template.not-enough-action-points-end-your-turn': string
  readonly 'profession-skill-template.return-anchor-row-column': string
  readonly 'relic-expansion-copy.a-probe-confirming-2-new-mines-grants': string
  readonly 'relic-expansion-copy.add-field-dressing-and-second-wind-chest': string
  readonly 'relic-expansion-copy.add-field-notes-and-rangefinder-to-future': string
  readonly 'relic-expansion-copy.add-reactive-shell-and-rescue-ribbon-shield': string
  readonly 'relic-expansion-copy.add-supply-cache-and-cache-guard-recover': string
  readonly 'relic-expansion-copy.cache-guard': string
  readonly 'relic-expansion-copy.collect-all-3-chests-on-a-floor': string
  readonly 'relic-expansion-copy.confirm-3-mines-on-a-floor-to': string
  readonly 'relic-expansion-copy.field-dressing': string
  readonly 'relic-expansion-copy.field-notes': string
  readonly 'relic-expansion-copy.first-chest-each-floor-restores-5-health': string
  readonly 'relic-expansion-copy.guardian-crests': string
  readonly 'relic-expansion-copy.once-per-expedition-survive-lethal-damage-with': string
  readonly 'relic-expansion-copy.prospector-seals': string
  readonly 'relic-expansion-copy.rangefinder': string
  readonly 'relic-expansion-copy.reactive-shell': string
  readonly 'relic-expansion-copy.rescue-ribbon': string
  readonly 'relic-expansion-copy.second-wind': string
  readonly 'relic-expansion-copy.supply-cache': string
  readonly 'relic-expansion-copy.surveyor-notes': string
  readonly 'relic-expansion-copy.survival-charms': string
  readonly 'relic-expansion-copy.survive-health-damage-to-gain-1-shield': string
  readonly 'relic-expansion-copy.the-first-chest-collected-each-floor-grants': string
  readonly 'relic-expansion-copy.the-first-shielded-mine-hit-each-floor': string
  readonly 'sonar-copy.already-scanned-reading-selected': string
  readonly 'sonar-copy.choose-send-pulse-then-a-center-square': string
  readonly 'sonar-copy.choose-the-center-of-a-3-3': string
  readonly 'sonar-copy.compare-echoes': string
  readonly 'sonar-copy.compare-two-echoes': string
  readonly 'sonar-copy.echo': string
  readonly 'sonar-copy.echo-log': string
  readonly 'sonar-copy.enlarge-squares': string
  readonly 'sonar-copy.every-echo-accounted-for': string
  readonly 'sonar-copy.exclusive-region': string
  readonly 'sonar-copy.fewest-moves-first-fewer-pulses-break-ties': string
  readonly 'sonar-copy.fit-board': string
  readonly 'sonar-copy.make-each-pulse-count': string
  readonly 'sonar-copy.mine-difference-outside-the-overlap': string
  readonly 'sonar-copy.mines': string
  readonly 'sonar-copy.moves': string
  readonly 'sonar-copy.no-pulses-left-four-safe-excavations-recharge': string
  readonly 'sonar-copy.one-echo-left-unanswered': string
  readonly 'sonar-copy.open-a-square-to-start': string
  readonly 'sonar-copy.open-the-board': string
  readonly 'sonar-copy.pulses-left': string
  readonly 'sonar-copy.pulses-used': string
  readonly 'sonar-copy.scan-target': string
  readonly 'sonar-copy.scan-to-open-the-center-mines-become': string
  readonly 'sonar-copy.select-a-square-to-open-it': string
  readonly 'sonar-copy.select-two-log-entries-their-shared-squares': string
  readonly 'sonar-copy.select-two-readings-to-compare-their-regions': string
  readonly 'sonar-copy.send-pulse': string
  readonly 'sonar-copy.shared-squares': string
  readonly 'sonar-copy.sonar': string
  readonly 'sonar-copy.spend-a-pulse': string
  readonly 'sonar-copy.start-with-three-pulses-four-safe-excavation': string
  readonly 'sonar-copy.the-first-opening-and-its-neighbors-are': string
  readonly 'sonar-copy.the-saved-puzzle-could-not-be-restored': string
  readonly 'sonar-copy.this-puzzle-reached-its-move-limit-start': string
  readonly 'sonar-copy.tutorial': string
  readonly 'sonar-copy.your-first-clear-belongs-here': string
  readonly 'sonar-copy.your-readings-will-appear-here': string
  readonly 'sonar-view.confirmed-mine': string
  readonly 'sonar-view.obscured-clue-scan-to-clarify': string
  readonly 'sonar-view.recharge': string
  readonly 'sonar-view.recharge-progress-label': string
  readonly 'tactical-copy.already-used-or-the-target-is-cleared': string
  readonly 'tactical-copy.anchors-recharge-after-the-lure-and-exposure': string
  readonly 'tactical-copy.approach-and-click-the-core-to-prime': string
  readonly 'tactical-copy.attack-avoided-or-blocked': string
  readonly 'tactical-copy.battle-in-progress-watch-the-attack-forecast': string
  readonly 'tactical-copy.braced-reduce-enemy-damage-by-3-this': string
  readonly 'tactical-copy.calibration-failed-5-damage': string
  readonly 'tactical-copy.choose-a-reachable-cell': string
  readonly 'tactical-copy.core-overloaded-three-turn-strike-window': string
  readonly 'tactical-copy.core-primed-strike-window-open': string
  readonly 'tactical-copy.cost-ap': string
  readonly 'tactical-copy.deduce-and-destroy-nests-to-weaken-the': string
  readonly 'tactical-copy.disable-both-shield-pylons-first': string
  readonly 'tactical-copy.disable-the-seal-in-the-opposite-realm': string
  readonly 'tactical-copy.egg-destroyed-hatching-prevented': string
  readonly 'tactical-copy.enemy-attack-hit': string
  readonly 'tactical-copy.flag-all-mines-around-the-target-first': string
  readonly 'tactical-copy.grounded-resist-the-pulse-and-reduce-enemy': string
  readonly 'tactical-copy.hatchling-intercepted-attack-cancelled': string
  readonly 'tactical-copy.lure-locked-clear-the-gold-route': string
  readonly 'tactical-copy.lure-the-knight-into-an-anchor-to': string
  readonly 'tactical-copy.magnetic-displacement-resisted': string
  readonly 'tactical-copy.move-next-to-the-target-first': string
  readonly 'tactical-copy.needs-ap-shorten-the-route-or-end': string
  readonly 'tactical-copy.nest-destroyed-supply-stopped-queen-armor-and': string
  readonly 'tactical-copy.one-twin-defeated-the-survivor-s-future': string
  readonly 'tactical-copy.open-a-route-of-at-least-two': string
  readonly 'tactical-copy.realm-shifted-the-turn-continues': string
  readonly 'tactical-copy.reflection-active-shift-and-strike-the-other': string
  readonly 'tactical-copy.return-a-spell-with-an-hourglass-to': string
  readonly 'tactical-copy.strike-landed-damage': string
  readonly 'tactical-copy.web-cleared-lane-open': string
  readonly 'tactical-template.ap-left': string
  readonly 'tactical-template.battle-reference': string
  readonly 'tactical-template.prime-core-1-ap': string
  readonly 'tactical-template.replay-arrival': string
  readonly 'tactical-template.shift-realm-1-ap': string
  readonly 'templates.learn-to-play': string
  readonly 'title-copy.attack-1-against-a-boss-at-half': string
  readonly 'title-copy.attack-1-while-your-health-is-at': string
  readonly 'title-copy.attack-2-against-the-brood-queen-while': string
  readonly 'title-copy.attack-2-while-the-magnetic-knight-is': string
  readonly 'title-copy.completing-your-profession-skill-in-battle-refunds': string
  readonly 'title-copy.completing-your-profession-skill-restores-1-health': string
  readonly 'title-copy.defense-1-in-the-brood-queen-battle': string
  readonly 'title-copy.defense-1-while-braced': string
  readonly 'title-copy.defense-1-while-your-health-is-at': string
  readonly 'title-copy.depart-with-1-extra-probe-up-to': string
  readonly 'title-copy.depart-with-1-extra-scanner-up-to': string
  readonly 'title-copy.entering-floors-4-and-7-each-adds': string
  readonly 'title-copy.every-third-boss-turn-starts-with-1': string
  readonly 'title-copy.gain-1-shield-when-entering-a-boss': string
  readonly 'title-copy.maximum-health-1-for-this-expedition': string
  readonly 'title-copy.recover-2-health-when-entering-a-boss': string
  readonly 'title-copy.the-first-chest-each-floor-restores-1': string
  readonly 'title-copy.the-first-turn-of-each-boss-battle': string
  readonly 'title-copy.the-first-two-chests-of-the-expedition': string
  readonly 'title-copy.the-third-chest-of-the-expedition-grants': string
  readonly 'title-copy.with-3-or-more-relics-reward-offers': string
  readonly 'title-copy.with-fewer-than-3-relics-reward-offers': string
  readonly 'title-template.choose-a-title': string
  readonly 'title-template.earn-titles-through-achievements': string
  readonly 'title-template.expedition-title': string
  readonly 'title-template.no-title': string
  readonly 'title-template.no-titles-earned-yet': string
  readonly 'tutorial-lessons.a-probe-looks-ahead': string
  readonly 'tutorial-lessons.a-quiet-first-step': string
  readonly 'tutorial-lessons.alternate-between-local-clues-and-proven-mines': string
  readonly 'tutorial-lessons.bring-the-discovery-across': string
  readonly 'tutorial-lessons.choose-when-to-descend': string
  readonly 'tutorial-lessons.classic-first-field': string
  readonly 'tutorial-lessons.clear-the-blur': string
  readonly 'tutorial-lessons.cycle-to-quick-open-you-will-pass': string
  readonly 'tutorial-lessons.expedition-leave-camp': string
  readonly 'tutorial-lessons.explore-from-your-route': string
  readonly 'tutorial-lessons.finish-with-confidence': string
  readonly 'tutorial-lessons.flag-the-glowing-covered-square-a-flag': string
  readonly 'tutorial-lessons.keep-both-boards-in-view': string
  readonly 'tutorial-lessons.leave-a-reliable-mark': string
  readonly 'tutorial-lessons.make-a-second-deduction': string
  readonly 'tutorial-lessons.most-numbered-squares-are-obscured-select-sonar': string
  readonly 'tutorial-lessons.move-to-the-glowing-open-square-your': string
  readonly 'tutorial-lessons.one-button-four-actions': string
  readonly 'tutorial-lessons.open-a-safe-neighborhood': string
  readonly 'tutorial-lessons.open-the-glowing-square-empty-ground-opens': string
  readonly 'tutorial-lessons.open-the-matching-glowing-square-on-b': string
  readonly 'tutorial-lessons.open-the-route': string
  readonly 'tutorial-lessons.press-the-action-button-once-to-select': string
  readonly 'tutorial-lessons.quick-open-this-1-its-flagged-neighbor': string
  readonly 'tutorial-lessons.reach-the-treasure': string
  readonly 'tutorial-lessons.read-the-neighborhood': string
  readonly 'tutorial-lessons.reveal-this-frontier-square-your-explorer-first': string
  readonly 'tutorial-lessons.select-the-matching-flag-on-a-once': string
  readonly 'tutorial-lessons.select-the-probe-then-the-glowing-square': string
  readonly 'tutorial-lessons.select-the-scanner-then-any-glowing-square': string
  readonly 'tutorial-lessons.select-the-stairs-deliberately-to-leave-the': string
  readonly 'tutorial-lessons.select-this-1-to-inspect-its-eight': string
  readonly 'tutorial-lessons.sonar-read-the-echoes': string
  readonly 'tutorial-lessons.start-with-3-pulses-four-successful-safe': string
  readonly 'tutorial-lessons.survey-a-whole-row': string
  readonly 'tutorial-lessons.test-the-other-side': string
  readonly 'tutorial-lessons.the-revealed-1-diagonally-above-right-of': string
  readonly 'tutorial-lessons.the-two-boards-never-have-mines-at': string
  readonly 'tutorial-lessons.twin-two-sides-of-a-clue': string
  readonly 'tutorial-lessons.use-explorer-s-light-it-surveys-the': string
  readonly 'tutorial-lessons.use-quick-open-on-this-1-its': string
  readonly 'tutorial-lessons.walk-to-the-glowing-chest-to-collect': string
  readonly 'tutorial-lessons.you-are-on-the-board': string
  readonly 'tutorial-lessons.you-can-move-scout-collect-and-descend': string
  readonly 'tutorial-lessons.you-read-clues-marked-mines-and-opened': string
  readonly 'tutorial-lessons.your-profession-has-a-skill': string
  readonly 'tutorial-player.back-to-game': string
  readonly 'tutorial-player.chests': string
  readonly 'tutorial-player.click-tap-arrows-enter': string
  readonly 'tutorial-player.column': string
  readonly 'tutorial-player.continue': string
  readonly 'tutorial-player.covered': string
  readonly 'tutorial-player.exit-practice': string
  readonly 'tutorial-player.flag': string
  readonly 'tutorial-player.good-continue-when-you-are-ready': string
  readonly 'tutorial-player.learn-by-doing': string
  readonly 'tutorial-player.light': string
  readonly 'tutorial-player.practice-field': string
  readonly 'tutorial-player.probe': string
  readonly 'tutorial-player.ready-for-the-field': string
  readonly 'tutorial-player.row': string
  readonly 'tutorial-player.scan': string
  readonly 'tutorial-player.sonar': string
  readonly 'tutorial-player.start-again': string
  readonly 'tutorial-player.try-here': string
  readonly 'tutorial-player.try-the-highlighted-action-first-nothing-was': string
  readonly 'variant-app.battle-reference': string
  readonly 'variant-copy.1-loadout-point-starting-probes-1': string
  readonly 'variant-copy.1-loadout-point-starting-scans-1': string
  readonly 'variant-copy.1-probe-1-scan-1-shield': string
  readonly 'variant-copy.1-probe-1-shield-each-floor-1': string
  readonly 'variant-copy.1-probe-2-scans': string
  readonly 'variant-copy.1-probe-on-each-new-floor-up': string
  readonly 'variant-copy.1-probe-scout-a-chest-each-floor': string
  readonly 'variant-copy.1-scan-on-each-new-floor-up': string
  readonly 'variant-copy.2-loadout-points-starting-shields-1': string
  readonly 'variant-copy.2-probes-1-scan': string
  readonly 'variant-copy.2-shields-each-floor-1-shield-1': string
  readonly 'variant-copy.abyss': string
  readonly 'variant-copy.abyss-hourglass': string
  readonly 'variant-copy.achievement-exclusive-clear-50-floors-and-claim': string
  readonly 'variant-copy.achievement-exclusive-confirm-5-unique-mines-in': string
  readonly 'variant-copy.achievement-exclusive-the-first-chest-collected-each': string
  readonly 'variant-copy.add-exit-compass-and-salvage-seal-to': string
  readonly 'variant-copy.advanced': string
  readonly 'variant-copy.aegis': string
  readonly 'variant-copy.alchemist': string
  readonly 'variant-copy.an-incompatible-or-damaged-save-was-ignored': string
  readonly 'variant-copy.archaeologist': string
  readonly 'variant-copy.arrows-home-end-move-focus-enter-space': string
  readonly 'variant-copy.at-each-coordinate-at-most-one-board': string
  readonly 'variant-copy.banked-supplies': string
  readonly 'variant-copy.base-camp': string
  readonly 'variant-copy.base-settlement': string
  readonly 'variant-copy.begin-expedition': string
  readonly 'variant-copy.camp-and-results-preserved-the-previous-dungeon': string
  readonly 'variant-copy.camp-facilities': string
  readonly 'variant-copy.chest-beacon': string
  readonly 'variant-copy.choose-a-relic': string
  readonly 'variant-copy.choose-one-relic-for-the-next-floor': string
  readonly 'variant-copy.choose-the-first-opening-on-either-board': string
  readonly 'variant-copy.choose-your-difficulty-and-expedition-length-build': string
  readonly 'variant-copy.classic': string
  readonly 'variant-copy.click-revealed-floor-to-walk-there-along': string
  readonly 'variant-copy.collect-a-chest-to-scout-the-next': string
  readonly 'variant-copy.collected': string
  readonly 'variant-copy.completed-expeditions': string
  readonly 'variant-copy.completing-a-profession-skill-scouts-your-landing': string
  readonly 'variant-copy.confirm-4-distinct-mines-in-a-floor': string
  readonly 'variant-copy.confirm-8-distinct-mines-in-a-floor': string
  readonly 'variant-copy.confirmed-mine-locked-flag': string
  readonly 'variant-copy.confirmed-safe': string
  readonly 'variant-copy.continue-to-next-floor': string
  readonly 'variant-copy.difficulty': string
  readonly 'variant-copy.difficulty-bonus': string
  readonly 'variant-copy.difficulty-reward': string
  readonly 'variant-copy.drag-a-tool-onto-the-board-or': string
  readonly 'variant-copy.end-this-expedition-and-bank-all-collected': string
  readonly 'variant-copy.engineer': string
  readonly 'variant-copy.entrance': string
  readonly 'variant-copy.exit': string
  readonly 'variant-copy.exit-compass': string
  readonly 'variant-copy.expedition': string
  readonly 'variant-copy.expedition-complete': string
  readonly 'variant-copy.expedition-ended': string
  readonly 'variant-copy.expert': string
  readonly 'variant-copy.explorer': string
  readonly 'variant-copy.explorer-2': string
  readonly 'variant-copy.extract-to-camp': string
  readonly 'variant-copy.fault-map': string
  readonly 'variant-copy.field-radio': string
  readonly 'variant-copy.find-a-safe-route-to-the-exit': string
  readonly 'variant-copy.find-your-first-relic-after-floor-one': string
  readonly 'variant-copy.fit-board': string
  readonly 'variant-copy.floor': string
  readonly 'variant-copy.floor-cleared': string
  readonly 'variant-copy.future-treasures-give-9-supplies-instead-of': string
  readonly 'variant-copy.gain-1-shield-up-to-2-absorbs': string
  readonly 'variant-copy.game-mode': string
  readonly 'variant-copy.game-updated-your-expedition-returned-to-camp': string
  readonly 'variant-copy.guard': string
  readonly 'variant-copy.health': string
  readonly 'variant-copy.hunter-seal': string
  readonly 'variant-copy.inspect-a-3-3-area-gold-flags': string
  readonly 'variant-copy.inspect-a-whole-row-gold-flags-mark': string
  readonly 'variant-copy.keep-75-of-collected-loot-on-defeat': string
  readonly 'variant-copy.lantern': string
  readonly 'variant-copy.larger-cells': string
  readonly 'variant-copy.last-bastion': string
  readonly 'variant-copy.loadout-3-points': string
  readonly 'variant-copy.matching-coordinate': string
  readonly 'variant-copy.mines-total': string
  readonly 'variant-copy.mission-exclusive-1-loadout-point-a-successful': string
  readonly 'variant-copy.mission-exclusive-clear-12-floors-and-claim': string
  readonly 'variant-copy.moves': string
  readonly 'variant-copy.original-rules': string
  readonly 'variant-copy.partner-cleared-flagged-mines-there-are-now': string
  readonly 'variant-copy.probe-3-3-area': string
  readonly 'variant-copy.probe-found-count-mines': string
  readonly 'variant-copy.probe-kit': string
  readonly 'variant-copy.probes': string
  readonly 'variant-copy.profession': string
  readonly 'variant-copy.pulse-coil': string
  readonly 'variant-copy.reachable-frontier': string
  readonly 'variant-copy.recent-results-this-mode': string
  readonly 'variant-copy.relaxed': string
  readonly 'variant-copy.relic-archive': string
  readonly 'variant-copy.relic-build': string
  readonly 'variant-copy.revive-at-3-hp-and-scout-your': string
  readonly 'variant-copy.riftwalker': string
  readonly 'variant-copy.run-loot': string
  readonly 'variant-copy.safely-extracted': string
  readonly 'variant-copy.salvage-seal': string
  readonly 'variant-copy.scan-a-row': string
  readonly 'variant-copy.scanner': string
  readonly 'variant-copy.scans': string
  readonly 'variant-copy.scout-the-exit-s-3-3-area': string
  readonly 'variant-copy.scroll-or-swipe-to-explore-the-enlarged': string
  readonly 'variant-copy.sentinel': string
  readonly 'variant-copy.shields': string
  readonly 'variant-copy.stairs-reachable-click-them-when-ready-to': string
  readonly 'variant-copy.standard': string
  readonly 'variant-copy.supplies': string
  readonly 'variant-copy.survey-lens': string
  readonly 'variant-copy.survey-token': string
  readonly 'variant-copy.surveyor': string
  readonly 'variant-copy.survive-health-damage-with-2-hp-or': string
  readonly 'variant-copy.this-run-reached-the-move-limit-extract': string
  readonly 'variant-copy.trail-heart': string
  readonly 'variant-copy.treasure-pouch': string
  readonly 'variant-copy.treasure-safe': string
  readonly 'variant-copy.triggered-mine': string
  readonly 'variant-copy.twin-boards': string
  readonly 'variant-copy.unlock-at-camp': string
  readonly 'variant-copy.unlock-departure-equipment-choose-up-to-3': string
  readonly 'variant-copy.unlocked': string
  readonly 'variant-copy.used-this-expedition': string
  readonly 'variant-copy.used-this-floor': string
  readonly 'variant-copy.used-this-turn': string
  readonly 'variant-copy.view-results': string
  readonly 'variant-copy.wall-impassable': string
  readonly 'variant-copy.waymarker': string
  readonly 'variant-copy.workshop': string
  readonly 'variant-copy.your-story-starts-here': string
  readonly 'variant-view.resonator-four-turn-core-windows': string
  readonly 'variant-view.return-anchor': string
  readonly 'variant-view.rift-landing': string
  readonly 'variant-view.suppressor-lowers-future-attacks-to-3': string
  readonly 'variant-view.two-way-rift': string
}

/** Named substitutions are plain text; the renderer owns HTML escaping. */
export interface MessageParameters {
  readonly [name: string]: string | number
}
export type MessageKey = keyof MessageCatalog
